@startuml
       Alice -> Bob: 认证
       Bob --> Alice: Authentication Response

              Alice -> Bob: Another authentication Request
              Alice <-- Bob: another authentication Response
       @enduml